name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag master HEAD
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git tag "${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"
